In [20]:
import numpy as p
import tensorflow as tf
import numpy as np
import tqdm
import pandas as pd
import utils

In [21]:
Y_df, R_df = utils.load_ratings_small('data/ml-latest-small', count=2000)

0it [00:00, ?it/s]

2000it [00:01, 1047.95it/s]

In [22]:
Y_df.head()

,movieId,title,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,1,Toy Story (1995),4.0,0.0,0.0,0.0,4.0,0.0,4.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.5,0.0,4.5,3.5
1,2,Jumanji (1995),0.0,0.0,0.0,0.0,0.0,4.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
2,3,Grumpier Old Men (1995),4.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4,Waiting to Exhale (1995),0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0
4,5,Father of the Bride Part II (1995),0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [23]:
Y = Y_df.drop(Y_df.columns[0:2], axis=1, inplace=False).to_numpy()
R = R_df.drop(R_df.columns[0:2], axis=1, inplace=False).to_numpy()

In [24]:
num_features = 10
X, W, b, num_movies, num_users = utils.load_precalc_params(Y_df, num_features=num_features)

In [25]:
X_df = pd.DataFrame(X)
X_df

,0,1,2,3,4,5,6,7,8,9
0,0.600519,0.477275,0.120858,0.583450,0.025938,0.875390,0.863319,0.308272,0.046199,0.228535
1,0.100802,0.080574,0.803157,0.114011,0.447711,0.237283,0.733365,0.254978,0.567254,0.296067
2,0.147459,0.481953,0.817550,0.612584,0.872136,0.461091,0.728725,0.163299,0.002415,0.170263
3,0.661594,0.908556,0.287061,0.926564,0.594360,0.786604,0.476752,0.219439,0.774872,0.871008
4,0.858664,0.583643,0.223034,0.110805,0.748947,0.954375,0.716638,0.689170,0.924096,0.374018
...,...,...,...,...,...,...,...,...,...,...
9737,0.530437,0.672526,0.823983,0.557052,0.350813,0.970318,0.374414,0.123252,0.703312,0.533645
9738,0.618472,0.640962,0.626985,0.663214,0.323776,0.231737,0.336191,0.388560,0.174784,0.538338
9739,0.921511,0.791086,0.039381,0.885873,0.372178,0.775792,0.205621,0.385919,0.769015,0.668455
9740,0.091568,0.052256,0.304674,0.387521,0.037255,0.282203,0.963039,0.463975,0.711989,0.790977
9741,0.211236,0.122008,0.456401,0.705751,0.169804,0.021419,0.886911,0.936584,0.878289,0.692403

In [26]:
print("Y", Y.shape, "R", R.shape)
print("X", X.shape)
print("W", W.shape)
print("b", b.shape)
print("num_features", num_features)
print("num_movies",   num_movies)
print("num_users",    num_users)

Y (9742, 18) R (9742, 18)
X (9742, 10)
W (20, 10)
b (1, 20)
num_features 10
num_movies 9742
num_users 20

In [27]:
# Reduce the data set size so that this runs faster
num_users_r = 4
num_movies_r = 5 
num_features_r = 3

X_r = X[:num_movies_r, :num_features_r]
W_r = W[:num_users_r,  :num_features_r]
b_r = b[0, :num_users_r].reshape(1,-1)
Y_r = Y[:num_movies_r, :num_users_r]
R_r = R[:num_movies_r, :num_users_r]

# Evaluate cost function
J = utils.cofi_cost_func_v(X_r, W_r, b_r, Y_r, R_r, 0)
print(f"Cost: {J:0.2f}")

Cost: 9.88

In [28]:
# Evaluate cost function with regularization 
J = utils.cofi_cost_func_v(X_r, W_r, b_r, Y_r, R_r, 1.5)
print(f"Cost (with regularization): {J:0.2f}")

Cost (with regularization): 17.43

In [29]:
my_ratings = np.zeros(num_movies)  

my_ratings[43] = 4   #  Se7en
my_ratings[7258] = 5   #  Shutter Island
my_ratings[2439] = 5   #  Scent of a Woman
my_ratings[15] = 5   #  Casino
my_ratings[914] = 5   #  Goodfellas
my_ratings[3167] = 5   #  Scarface
my_ratings[98] = 5   #  Taxi driver
my_ratings[4167] = 3   #  King of comedy
my_ratings[8305] = 5   #  Wolf of Wall Street
my_ratings[8376] = 5   #  Interstellar
my_ratings[1481] = 2   #  Mask of Zorro
my_rated = [i for i in range(len(my_ratings)) if my_ratings[i] > 0]
print('\nNew user ratings:\n')
for i in range(len(my_ratings)):
    if my_ratings[i] > 0 :
        print(f'Rated {my_ratings[i]} for  {Y_df.loc[i,"title"]}')

New user ratings:

Rated 5.0 for  Casino (1995)
Rated 4.0 for  Seven (a.k.a. Se7en) (1995)
Rated 5.0 for  Taxi Driver (1976)
Rated 5.0 for  Goodfellas (1990)
Rated 2.0 for  Mask of Zorro, The (1998)
Rated 5.0 for  Scent of a Woman (1992)
Rated 5.0 for  Scarface (1983)
Rated 3.0 for  King of Comedy, The (1983)
Rated 5.0 for  Shutter Island (2010)
Rated 5.0 for  Wolf of Wall Street, The (2013)
Rated 5.0 for  Interstellar (2014)

In [30]:
# Add new user ratings 
Y = np.c_[my_ratings, Y]
R = np.c_[(my_ratings != 0).astype(int), R]

In [31]:
Ynorm, Ymean = utils.normalize_ratings(Y, R)
Ynorm

c:\Users\User\Github_Repositories\learning-ml\courses\Unsupervised-Learning-Recommenders-Reinforcement-Learning\.venv\lib\site-packages\numpy\core\fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
c:\Users\User\Github_Repositories\learning-ml\courses\Unsupervised-Learning-Recommenders-Reinforcement-Learning\.venv\lib\site-packages\numpy\core\_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

array([[ 0.        ,  0.16666667,  0.        , ...,  0.        ,
         0.66666667, -0.33333333],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        , -0.66666667],
       [ 0.        , -0.5       ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]])

In [32]:
import keras

#  Useful Values
num_movies, num_users = Y.shape
num_features = 100

# Set Initial Parameters (W, X), use tf.Variable to track these variables
tf.random.set_seed(1234) # for consistent results
W = tf.Variable(tf.random.normal((num_users,  num_features),dtype=tf.float64),  name='W')
X = tf.Variable(tf.random.normal((num_movies, num_features),dtype=tf.float64),  name='X')
b = tf.Variable(tf.random.normal((1,          num_users),   dtype=tf.float64),  name='b')

# Instantiate an optimizer.
optimizer = keras.optimizers.Adam(learning_rate=1e-1)

In [33]:
iterations = 1000
lambda_ = 1
for iter in range(iterations):
    # Use TensorFlow’s GradientTape
    # to record the operations used to compute the cost 
    with tf.GradientTape() as tape:

        # Compute the cost (forward pass included in cost)
        cost_value = utils.cofi_cost_func_v(X, W, b, Ynorm, R, lambda_)

    # Use the gradient tape to automatically retrieve
    # the gradients of the trainable variables with respect to the loss
    grads = tape.gradient( cost_value, [X,W,b] )

    # Run one step of gradient descent by updating
    # the value of the variables to minimize the loss.
    optimizer.apply_gradients( zip(grads, [X,W,b]) )

    # Log periodically.
    if iter % 20 == 0:
        print(f"Training loss at iteration {iter}: {cost_value:0.1f}")

Training loss at iteration 0: 593592.4
Training loss at iteration 20: 35722.3
Training loss at iteration 40: 7812.1
Training loss at iteration 60: 1994.1
Training loss at iteration 80: 699.5
Training loss at iteration 100: 326.6
Training loss at iteration 120: 194.6
Training loss at iteration 140: 141.0
Training loss at iteration 160: 117.2
Training loss at iteration 180: 106.0
Training loss at iteration 200: 100.4
Training loss at iteration 220: 97.3
Training loss at iteration 240: 95.5
Training loss at iteration 260: 94.3
Training loss at iteration 280: 93.5
Training loss at iteration 300: 92.9
Training loss at iteration 320: 92.5
Training loss at iteration 340: 92.2
Training loss at iteration 360: 91.9
Training loss at iteration 380: 91.8
Training loss at iteration 400: 91.6
Training loss at iteration 420: 91.5
Training loss at iteration 440: 91.4
Training loss at iteration 460: 91.3
Training loss at iteration 480: 91.2
Training loss at iteration 500: 91.2
Training loss at iteration 520: 91.1
Training loss at iteration 540: 91.1
Training loss at iteration 560: 91.1
Training loss at iteration 580: 91.0
Training loss at iteration 600: 91.0
Training loss at iteration 620: 91.0
Training loss at iteration 640: 91.0
Training loss at iteration 660: 91.0
Training loss at iteration 680: 90.9
Training loss at iteration 700: 90.9
Training loss at iteration 720: 90.9
Training loss at iteration 740: 90.9
Training loss at iteration 760: 90.9
Training loss at iteration 780: 90.9
Training loss at iteration 800: 90.9
Training loss at iteration 820: 90.9
Training loss at iteration 840: 90.9
Training loss at iteration 860: 90.9
Training loss at iteration 880: 90.9
Training loss at iteration 900: 90.9
Training loss at iteration 920: 90.9
Training loss at iteration 940: 90.8
Training loss at iteration 960: 90.8
Training loss at iteration 980: 90.8